version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "NCTU-BBS"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-njs0w35z2480"
s3_prefix = "NCTU-BBS"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"

