AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NCTU_BBS

Globals:
  Function:
    Timeout: 60

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: nctu-bbs-user-pool
      AutoVerifiedAttributes:
      - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 365

  UserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
      - USER_PASSWORD_AUTH

  UserPoolResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties: 
      Identifier: bbs.oscarhsu.me
      Name: nctu-bbs-resource-server
      Scopes: 
        - ScopeDescription: auth.token
          ScopeName: auth.token
      UserPoolId: !Ref UserPool

  BoardsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: name
          AttributeType: S
      KeySchema: 
        - AttributeName: name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: nctu-bbs-boards

  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: N
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: nctu-bbs-posts

  IdTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: name
          AttributeType: S
      KeySchema: 
        - AttributeName: name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: nctu-bbs-next-id

  NctuBBSApi:
    Type: AWS::Serverless::Api
    Properties:
      Domain: 
        CertificateArn: arn:aws:acm:ap-northeast-1:440374182634:certificate/3705c935-a0cf-4c05-a49a-19f84d98ae4b
        DomainName: bbs.oscarhsu.me
      StageName: dev
      Auth:
        Authorizers: 
          NctuBbsApiAuthorizer:
            Identity:
              Header: Auth
            UserPoolArn: !GetAtt UserPool.Arn


  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess

  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref NctuBBSApi

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/register/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Path: /register
            Method: post
            RestApiId: !Ref NctuBBSApi

  CreateBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create_board/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Auth:
              Authorizer: NctuBbsApiAuthorizer
            Path: /create-board
            Method: post
            RestApiId: !Ref NctuBBSApi

  CreatePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create_post/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Auth:
              Authorizer: NctuBbsApiAuthorizer
            Path: /create-post
            Method: post
            RestApiId: !Ref NctuBBSApi

  ListBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/list_board/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Path: /list-board
            Method: post
            RestApiId: !Ref NctuBBSApi

  ListPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/list_post/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Path: /list-post
            Method: post
            RestApiId: !Ref NctuBBSApi

  ReadPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/read/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Path: /read
            Method: post
            RestApiId: !Ref NctuBBSApi

  DeletePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delete_post/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Auth:
              Authorizer: NctuBbsApiAuthorizer
            Path: /delete-post
            Method: post
            RestApiId: !Ref NctuBBSApi

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Register:
          Type: Api
          Properties:
            Auth:
              Authorizer: NctuBbsApiAuthorizer
            Path: /update
            Method: post
            RestApiId: !Ref NctuBBSApi


Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for BBS Server"
    Value: "https://bbs.oscarhsu.me/"
  UserPoolClientId:
    Description: "User Pool Client Id"
    Value: !Ref UserPoolTokenClient
  UserPoolId:
    Description: "User Pool Id"
    Value: !Ref UserPool
